In-lyeog-sa-mu-so/jjoin-web

src/App.css, src/App.js, src/components/sidebar/Sidebar.jsx, src/components/sidebar/sidebar.css, src/pages/Notice/Board.jsx, src/pages/Notice/NoticeList/NoticeListPage.jsx, src/pages/Notice/NoticeReadPage.jsx, src/pages/Notice/NoticeUpdatePage.jsx, src/pages/Notice/NoticeWritePage.jsx, src/pages/decorate/DecoratePage.jsx, src/pages/decorate/DecorateUpdatePage.jsx
=> Feat: 공지사항 추가, CSS 반영

src/pages/decorate/DecorateBoard.jsx, src/pages/decorate/DecoratePage.jsx
=> ✨  feat: DecoratePage, 사진 불러오기

src/App.js, src/pages/Notice/NoticeUpdatePage.jsx, src/pages/decorate/DecorateBoard.jsx, src/pages/decorate/DecorateUpdatePage.jsx
=> ✨ ADD: Decoration, Decoration update

package.json, src/App.js, src/pages/calendar/Calendar.jsx, yarn.lock
캘린더 일정 수정 필요, 캘린더 UI css 입혀야 함
=> ✨ feat: 캘린더 일정 등록, 삭제 기능 추가

src/pages/decorate/DecorateBoard.jsx, src/pages/decorate/DecoratePage.jsx, src/pages/decorate/DecorateUpdatePage.jsx
=> ✨ feat: 홍보페이지 관리, 홍보페이지 수정 CSS

src/App.js, src/pages/Notice/Board.jsx, src/pages/Notice/NoticeList/NoticeListPage.jsx, src/pages/Notice/NoticeReadPage.jsx, src/pages/Notice/NoticeUpdatePage.jsx, src/pages/Notice/NoticeWritePage.jsx, src/pages/apply/ApplyFormMakePage.jsx, src/pages/decorate/DecorateBoard.jsx, src/pages/decorate/DecorateFixPage.jsx, src/pages/decorate/DecoratePage.jsx
=> ✨ Fix: mockserver Url

src/pages/apply/ApplyFormFixPage.jsx
=> ✨ ADD: ApplyFormFixPage.jsx

src/App.js, src/components/sidebar/Sidebar.jsx, src/components/sidebar/sidebar.css, src/pages/home/Home.jsx, src/state.js
시작화면 /manager로 설정, home화면 수정, sidebar 수정
=> ✨ FIX: home.jsx, sidebar.jsx

src/pages/apply/ApplyFormFixPage.jsx
=> ✨ Fix: ApplyFormPage.jsx

src/App.js, src/components/sidebar/Sidebar.jsx, src/pages/calendar/AddEvent.jsx, src/pages/calendar/EditEvent.jsx, src/pages/calendar/EventCalendar.jsx, src/pages/calendar/EventDetails.jsx
=> 🐛 fix: 캘린더 일정 등록, 조회, 수정, 삭제 수정

src/pages/Notice/Board.jsx, src/pages/Notice/NoticeList/NoticeListPage.jsx, src/pages/Notice/NoticeReadPage.jsx, src/pages/Notice/NoticeUpdatePage.jsx, src/pages/Notice/NoticeWritePage.jsx, src/pages/apply/ApplyFormFixPage.jsx, src/pages/apply/ApplyFormPage.jsx, src/pages/decorate/DecorateBoard.jsx, src/pages/decorate/DecorateFixPage.jsx, src/pages/decorate/DecoratePage.jsx, src/pages/home/Home.jsx
=> 💄 Fix: CSS 대량 수정

package.json, src/App.js, src/components/topbar/Topbar.jsx, src/pages/calendar/AddEvent.jsx, src/pages/calendar/EventCalendar.jsx, src/pages/calendar/EventDetails.jsx, src/state.js, yarn.lock
=> ✨ feat: 캘린더 일정 목록 조회, 일정 등록, 수정, 삭제 연동

src/components/sidebar/Sidebar.jsx, src/pages/calendar/AddEvent.jsx, src/pages/calendar/EditEvent.jsx, src/pages/calendar/EventDetails.jsx
캘린더 일정 상세보기 연동, 새로고침 시 사이드바 렌더링 안되는 버그 fix
=> ✨ feat: 캘린더 상세보기 연동 및 사이드바 렌더링

src/components/sidebar/sidebar.css, src/pages/Notice/NoticeList/NoticeListPage.jsx, src/pages/Notice/NoticeReadPage.jsx, src/pages/Notice/NoticeUpdatePage.jsx, src/pages/apply/ApplyFormFixPage.jsx, src/pages/apply/ApplyFormPage.jsx, src/pages/decorate/DecorateBoard.jsx, src/pages/decorate/DecorateFixPage.jsx, src/pages/decorate/DecoratePage.jsx, src/pages/home/Home.jsx
NoticeList 페이징 추가, 홍보페이지 기타 렌더링 이슈 수정
=> ✨ Add: NoticeList 페이징, 💄 : fix: 홍보페이지 수정

src/pages/userList/ApplicationList.jsx, src/pages/userList/UserList.jsx
더미 데이터만 넣어뒀습니다. 서버 연동 기능은 추가해야 합니다.
=> ✨ feat: 인원 관리, 가입 신청 관리(더미 데이터)

src/App.css, src/components/sidebar/Sidebar.jsx, src/components/sidebar/sidebar.css, src/components/topbar/topbar.css, src/pages/Notice/NoticeList/CommonTable.css, src/pages/Notice/NoticeList/NoticeListPage.jsx, src/pages/home/Home.jsx
=> 💄 fix: home, sidebar css 수정 

src/App.js, src/pages/Notice/NoticeList/NoticeListPage.jsx, src/pages/apply/ApplyFormAddPage.jsx, src/pages/apply/ApplyFormDeletePage.jsx, src/pages/apply/ApplyFormPage.jsx, src/pages/decorate/DecorateFixPage.jsx
NoticeLisPage 페이지 번호 개수 동적이도록 수정
=> 💄 fix: NoticeLisPage 페이지 번호 개수 동적이도록 수정

src/pages/apply/ApplyFormAddPage.jsx, src/pages/apply/ApplyFormDeletePage.jsx, src/pages/apply/ApplyFormFixPage.jsx, src/pages/apply/ApplyFormPage.jsx
=> 💄 Fix: ApplyForm 수정,추가,삭제 로직 구현

src/App.js, src/pages/userList/ApplicationDetail.jsx, src/pages/userList/ApplicationList.jsx, src/pages/userList/UserList.jsx
=> ✨ feat: 멤버 목록 조회, 멤버 직책 변경, 멤버 퇴출/가입신청서 조회, 가입 수락, 가입 거절 기능 구현

src/pages/decorate/DecorateFixPage.jsx, src/pages/home/Home.jsx
=> 💄 DecorateFixPage 수정 로직 구현

src/pages/Notice/NoticeUpdatePage.jsx, src/pages/Notice/NoticeWritePage.jsx, src/pages/apply/ApplyFormAddPage.jsx, src/pages/apply/ApplyFormDeletePage.jsx, src/pages/apply/ApplyFormFixPage.jsx, src/pages/apply/ApplyFormPage.jsx, src/pages/decorate/DecorateBoard.jsx, src/pages/decorate/DecorateFixPage.jsx
=> 💄 모든 Page 입력창 null 값일때 예외처리

src/pages/home/Home.jsx
=> 💄 Home.jsx css 수정
